### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by Wauro21** [JuanjoV/axi_transaction_timer#1]
![image](https://github.com/user-attachments/assets/a4cac14c-5ec3-4534-86b3-4678ef0b906c)

**Comment by Juanx65** [comment]
ese axi transacion timer esta aqui entre nosotros?
![image](https://github.com/user-attachments/assets/1b69e254-ea93-4d9f-a365-356040ef2110)

**Comment by JuanjoV** [comment]
Es una ilusión
